-- Profiles table to store user information
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  display_name text,
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Rooms table to track active chat groups
create table public.rooms (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  member_count int default 0 not null,
  status text default 'active' check (status in ('active', 'full', 'inactive'))
);

-- Messages table to store chat history
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  room_id uuid references public.rooms on delete cascade not null,
  user_id uuid not null, -- Can be from auth.users or a random uuid for guests
  user_name text not null,
  content text not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.messages enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Policies for rooms
create policy "Rooms are viewable by authenticated users." on public.rooms
  for select using (true);

create policy "Anyone can create a room." on public.rooms
  for insert with check (true);

create policy "Anyone can update room member count." on public.rooms
  for update using (true);

-- Policies for messages
create policy "Messages are viewable by everyone in the room." on public.messages
  for select using (true);

create policy "Anyone can insert messages." on public.messages
  for insert with check (true);

-- Function to handle new user profile creation
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user profile
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Atomic function to find and join an available room
create or replace function public.join_available_room(user_id uuid)
returns uuid as $$
declare
  target_room_id uuid;
begin
  -- Try to find an active room with space
  select id into target_room_id
  from public.rooms
  where status = 'active' and member_count < 5
  order by member_count desc
  limit 1
  for update; -- Lock the row to prevent race conditions

  if target_room_id is not null then
    -- Join existing room
    update public.rooms
    set member_count = member_count + 1
    where id = target_room_id;
  else
    -- Create new room
    insert into public.rooms (member_count, status)
    values (1, 'active')
    returning id into target_room_id;
  end if;

  return target_room_id;
end;
$$ language plpgsql security definer;

